openapi: 3.0.0
info:
  title: 문화재/축제 API
  description: 문화재 정보, 축제 정보, 계정 관리를 위한 API 문서
  version: 1.0.0

servers:
  - url: http://localhost:8000
    description: 개발 서버

# 태그 정의 추가
tags:
  - name: account
    description: 계정 관리 관련 API
  - name: inquiry
    description: 문화재 및 축제 조회 관련 API
  - name: favorite
    description: 즐겨찾기 관련 API

paths:
  /account/create:
    post:
      tags:
        - account
      summary: 계정 생성
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 사용자 이메일
                password:
                  type: string
                  description: 사용자 비밀번호
                name:
                  type: string
                  description: 사용자 이름
      responses:
        "201":
          description: 계정 생성 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Account created successfully"
        "400":
          description: 잘못된 요청
        "409":
          description: 이미 존재하는 이메일

  /account/login:
    post:
      tags:
        - account
      summary: 로그인
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 사용자 이메일
                password:
                  type: string
                  description: 사용자 비밀번호
      responses:
        "200":
          description: 로그인 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: JWT 토큰
                  user:
                    type: object
                    properties:
                      email:
                        type: string
                      name:
                        type: string
        "401":
          description: 인증 실패
        "500":
          description: 서버 오류

  /pgdb/accounts:
    get:
      tags:
        - account
      summary: 계정 목록 조회
      responses:
        "200":
          description: 계정 목록 조회 성공
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    uuid:
                      type: string
                    email:
                      type: string
                    username:
                      type: string
        "500":
          description: 서버 오류

  /pgdb/heritage:
    get:
      tags:
        - inquiry
      summary: 문화재 목록 조회
      responses:
        "200":
          description: 문화재 목록 조회 성공
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    heritageid:
                      type: string
                    ccbaasno:
                      type: string
                    ccbamnm1:
                      type: string
                    ccbalcad:
                      type: string
                    content:
                      type: string
                    imageurl:
                      type: string
        "500":
          description: 서버 오류

  /pgdb/festivals:
    get:
      tags:
        - inquiry
      summary: 축제 목록 조회
      parameters:
        - in: query
          name: year
          schema:
            type: integer
          description: 조회할 연도
        - in: query
          name: month
          schema:
            type: integer
          description: 조회할 월
      responses:
        "200":
          description: 축제 목록 조회 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  year:
                    type: integer
                  month:
                    type: integer
                  transformedResults:
                    type: array
                    items:
                      type: object
                      properties:
                        festivalid:
                          type: array
                          items:
                            type: string
                        programName:
                          type: array
                          items:
                            type: string
                        programContent:
                          type: array
                          items:
                            type: string
                        startDate:
                          type: array
                          items:
                            type: string
                        endDate:
                          type: array
                          items:
                            type: string
                        location:
                          type: array
                          items:
                            type: string
                        contact:
                          type: array
                          items:
                            type: string
                        sido:
                          type: array
                          items:
                            type: string
                        targetAudience:
                          type: array
                          items:
                            type: string
                        imageUrl:
                          type: array
                          items:
                            type: string
        "500":
          description: 서버 오류

  /pgdb/favoritelist:
    get:
      tags:
        - favorite
      summary: 즐겨찾기 목록 조회
      security:
        - bearerAuth: []
      responses:
        "200":
          description: 즐겨찾기 목록 조회 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  festivals:
                    type: array
                    items:
                      type: object
                      properties:
                        user_id:
                          type: string
                        user_email:
                          type: string
                        favoriteid:
                          type: string
                        type:
                          type: string
                        festivalid:
                          type: string
                        festivalname:
                          type: string
                        festivalcontent:
                          type: string
                        festivallocation:
                          type: string
                        festivalstartdate:
                          type: string
                        festivalenddate:
                          type: string
                        festivaltargetaudience:
                          type: string
                        festivalcontact:
                          type: string
                        festivalimageurl:
                          type: string
                  heritages:
                    type: array
                    items:
                      type: object
                      properties:
                        user_id:
                          type: string
                        user_email:
                          type: string
                        favoriteid:
                          type: string
                        type:
                          type: string
                        heritageid:
                          type: string
                        heritagename:
                          type: string
                        heritageaddress:
                          type: string
                        heritagecontent:
                          type: string
                        heritagecccename:
                          type: string
                        heritageimageurl:
                          type: string
                        heritagelatitude:
                          type: string
                        heritagelongitude:
                          type: string
        "401":
          description: 인증 실패
        "500":
          description: 서버 오류

    post:
      tags:
        - favorite
      summary: 즐겨찾기 추가
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                type:
                  type: string
                  enum: [event, heritage]
      responses:
        "201":
          description: 즐겨찾기 추가 성공
        "400":
          description: 잘못된 요청
        "401":
          description: 인증 실패
        "500":
          description: 서버 오류

    delete:
      tags:
        - favorite
      summary: 즐겨찾기 삭제
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                type:
                  type: string
                  enum: [event, heritage]
      responses:
        "200":
          description: 즐겨찾기 삭제 성공
        "400":
          description: 잘못된 요청
        "401":
          description: 인증 실패
        "500":
          description: 서버 오류

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
